### ISSUE TITLE
Maven site build fails

### ISSUE THREAD

**Issue by DirkMahler** [buschmais/jqassistant#131]
If a maven project is configured to use jQAssistant the following will not work:

```
mvn clean install site
```

```
-- [ERROR] Failed to execute goal 
org.apache.maven.plugins:maven-site-plugin:3.2:site (default-site) on project xyz: Error during page generation: Error rendering Maven report: 
/local/work/workspace/xyz/trunk/xyz/target/jqassistant/jqassistant-report.xml does not exist or is not a file. -> [Help 1]
```

Splitting up the execution works:

```
mvn clean install
mvn site
```

**Comment by toisrael** [comment]
I run into the sme problem. Project structure:


```
|--pom.xml
|--myproject-version-pom
      |--pom.xml
|--myproject-parent-pom
     |--pom.xml (<- containing the jQAssistant plugin and is child of myproject-version-pom)
```

Even if I build in two steps (as proposed here) the error occours. After `mvn install` there is a directory `jqassistant` in the target directory of `myproject-version-pom' but no report file at all.

Stacktrace:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project myproject-version-pom: Error during page generation: Error rendering Maven report: D:\myproject\15.200.0.0\myproject\myproject-version-pom\target\jqassistant\jqassistant-report.xml does not exist or is not a file. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project myproject-version-pom: Error during page generation
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:94)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:619)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error during page generation
	at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:143)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: org.apache.maven.doxia.siterenderer.RendererException: Error rendering Maven report: D:\myproject\15.200.0.0\myproject\myproject-version-pom\target\jqassistant\jqassistant-report.xml does not exist or is not a file.
	at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:233)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:319)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:135)
	at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:175)
	at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:138)
	... 21 more
Caused by: org.apache.maven.reporting.MavenReportException: D:\myproject\15.200.0.0\myproject\myproject-version-pom\target\jqassistant\jqassistant-report.xml does not exist or is not a file.
	at com.buschmais.jqassistant.scm.maven.ReportMojo.executeReport(ReportMojo.java:71)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:135)
	at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:228)
	... 25 more
```
