### ISSUE TITLE
Binary Version RC1 fails to scan with stackoverflow error

### ISSUE THREAD

**Issue by geraldglennon** [buschmais/jqassistant#204]
Using binary jqassistant.distribution-1.0.0-RC1 and scan a folder with a large amount of jar files causes jqassistant to fail. The previous release version jqassistant.distribution-1.0.0-M4 works perfectly and im current stuck using this version. But the new release does not. 

OS is Linux redhat  

StackTrace:
Exception in thread "main" java.lang.StackOverflowError
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.getScannerPluginsForType(ScannerImpl.java:153)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:52)
        at com.buschmais.jqassistant.plugin.cdi.impl.scanner.BeansXmlScannerPlugin.scan(BeansXmlScannerPlugin.java:51)
        at com.buschmais.jqassistant.plugin.cdi.impl.scanner.BeansXmlScannerPlugin.scan(BeansXmlScannerPlugin.java:29)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:59)
        at com.buschmais.jqassistant.plugin.cdi.impl.scanner.BeansXmlScannerPlugin.scan(BeansXmlScannerPlugin.java:51)
        at com.buschmais.jqassistant.plugin.cdi.impl.scanner.BeansXmlScannerPlugin.scan(BeansXmlScannerPlugin.java:29)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:59)
        at com.buschmais.jqassistant.plugin.cdi.impl.scanner.BeansXmlScannerPlugin.scan(BeansXmlScannerPlugin.java:51)
        at com.buschmais.jqassistant.plugin.cdi.impl.scanner.BeansXmlScannerPlugin.scan(BeansXmlScannerPlugin.java:29)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:59)
        at com.buschmais.jqassistant.plugin.cdi.impl.scanner.BeansXmlScannerPlugin.scan(BeansXmlScannerPlugin.java:51)
        at com.buschmais.jqassistant.plugin.cdi.impl.scanner.BeansXmlScannerPlugin.scan(BeansXmlScannerPlugin.java:29)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:59)
        at com.buschmais.jqassistant.plugin.cdi.impl.scanner.BeansXmlScannerPlugin.scan(BeansXmlScannerPlugin.java:51)
        at com.buschmais.jqassistant.plugin.cdi.impl.scanner.BeansXmlScannerPlugin.scan(BeansXmlScannerPlugin.java:29)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:59)
        at com.buschmais.jqassistant.plugin.cdi.impl.scanner.BeansXmlScannerPlugin.scan(BeansXmlScannerPlugin.java:51)
        at com.buschmais.jqassistant.plugin.cdi.impl.scanner.BeansXmlScannerPlugin.scan(BeansXmlScannerPlugin.java:29)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:59)
        at com.buschmais.jqassistant.plugin.cdi.impl.scanner.BeansXmlScannerPlugin.scan(BeansXmlScannerPlugin.java:51)
        at com.buschmais.jqassistant.plugin.cdi.impl.scanner.BeansXmlScannerPlugin.scan(BeansXmlScannerPlugin.java:29)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:59)
        at com.buschmais.jqassistant.plugin.cdi.impl.scanner.BeansXmlScannerPlugin.scan(BeansXmlScannerPlugin.java:51)
        at com.buschmais.jqassistant.plugin.cdi.impl.scanner.BeansXmlScannerPlugin.scan(BeansXmlScannerPlugin.java:29)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:59)
        at com.buschmais.jqassistant.plugin.cdi.impl.scanner.BeansXmlScannerPlugin.scan(BeansXmlScannerPlugin.java:51)
        at com.buschmais.jqassistant.plugin.cdi.impl.scanner.BeansXmlScannerPlugin.scan(BeansXmlScannerPlugin.java:29)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:59)
        at com.buschmais.jqassistant.plugin.cdi.impl.scanner.BeansXmlScannerPlugin.scan(BeansXmlScannerPlugin.java:51)
        at com.buschmais.jqassistant.plugin.cdi.impl.scanner.BeansXmlScannerPlugin.scan(BeansXmlScannerPlugin.java:29)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:59)
        at com.buschmais.jqassistant.plugin.cdi.impl.scanner.BeansXmlScannerPlugin.scan(BeansXmlScannerPlugin.java:51)
        at com.buschmais.jqassistant.plugin.cdi.impl.scanner.BeansXmlScannerPlugin.scan(BeansXmlScannerPlugin.java:29)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:59)
        at com.buschmais.jqassistant.plugin.cdi.impl.scanner.BeansXmlScannerPlugin.scan(BeansXmlScannerPlugin.java:51)
        at com.buschmais.jqassistant.plugin.cdi.impl.scanner.BeansXmlScannerPlugin.scan(BeansXmlScannerPlugin.java:29)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:59)
        at com.buschmais.jqassistant.plugin.cdi.impl.scanner.BeansXmlScannerPlugin.scan(BeansXmlScannerPlugin.java:51)
        at com.buschmais.jqassistant.plugin.cdi.impl.scanner.BeansXmlScannerPlugin.scan(BeansXmlScannerPlugin.java:29)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:59)
        at com.buschmais.jqassistant.plugin.cdi.impl.scanner.BeansXmlScannerPlugin.scan(BeansXmlScannerPlugin.java:51)
        at com.buschmais.jqassistant.plugin.cdi.impl.scanner.BeansXmlScannerPlugin.scan(BeansXmlScannerPlugin.java:29)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:59)
        at com.buschmais.jqassistant.plugin.cdi.impl.scanner.BeansXmlScannerPlugin.scan(BeansXmlScannerPlugin.java:51)
        at com.buschmais.jqassistant.plugin.cdi.impl.scanner.BeansXmlScannerPlugin.scan(BeansXmlScannerPlugin.java:29)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:59)
        at com.buschmais.jqassistant.plugin.cdi.impl.scanner.BeansXmlScannerPlugin.scan(BeansXmlScannerPlugin.java:51)
        at com.buschmais.jqassistant.plugin.cdi.impl.scanner.BeansXmlScannerPlugin.scan(BeansXmlScannerPlugin.java:29)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:59)
        at com.buschmais.jqassistant.plugin.cdi.impl.scanner.BeansXmlScannerPlugin.scan(BeansXmlScannerPlugin.java:51)
        at com.buschmais.jqassistant.plugin.cdi.impl.scanner.BeansXmlScannerPlugin.scan(BeansXmlScannerPlugin.java:29)

**Comment by DirkMahler** [comment]
Are you able to reproduce it with a current snapshot? You can fetch the latest distribution ZIP from https://oss.sonatype.org/content/repositories/snapshots/com/buschmais/jqassistant/distribution/jqassistant.distribution/1.0.0-RC2-SNAPSHOT?

**Comment by geraldglennon** [comment]
Hi Dirk,
I ran the snapshot version and it ran successfully. So it looks like its might be fine in this snapshot version.

I had to up the java heap size also. 

When will this version be released?

**Comment by DirkMahler** [comment]
The release is scheduled for the end of this week (Apr 17th 2015).
