### ISSUE TITLE
Exceptions are logged while scanning JUnit test reports

### ISSUE THREAD

**Issue by DirkMahler** [buschmais/jqassistant#210]
During a Maven build which creates JUnit test reports (surefire and failsafe) the following exception can be observed:
```
[ERROR] Cannot scan item /TEST-org.apache.tamaya.resolver.ConfigResolutionTest.xml
java.io.IOException: Cannot read XML document.
        at com.buschmais.jqassistant.plugin.junit.impl.scanner.TestReportScannerPlugin.scan(TestReportScannerPlugin.java:122)
        at com.buschmais.jqassistant.plugin.junit.impl.scanner.TestReportScannerPlugin.scan(TestReportScannerPlugin.java:28)
...
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[73,18]
Message: Verarbeitungsanweisungsziel, das "[xX][mM][lL]" entspricht, ist nicht zulässig.
        at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:601)
        at com.sun.xml.internal.stream.XMLEventReaderImpl.nextEvent(XMLEventReaderImpl.java:83)
        at com.buschmais.jqassistant.plugin.junit.impl.scanner.TestReportScannerPlugin.scan(TestReportScannerPlugin.java:51)
```

**Comment by DirkMahler** [comment]
Despite the logged exception data is correctly written to the database.
