### ISSUE TITLE
Exception while trying Getting Started example with 1.1.0.RC1

### ISSUE THREAD

**Issue by gavin834** [buschmais/jqassistant#282]
Running the Command Line Getting Started example scan step
bin\jqassistant.cmd scan -f lib
fails with an IllegalStateException. Root exception seems to be NullPointerException while parsing FastInfoset:jar:1.2.12.

Exception:

Exception in thread "main" java.lang.IllegalStateException: Unexpected problem w
hile scanning: item='lib', path='C:\jQAssistant\jqassistant.distribution-1.1.0-R
C1-bin\jqassistant.distribution-1.1.0-RC1\lib', scope='NONE', pipeline='[com.bus
chmais.jqassistant.plugin.common.impl.scanner.DirectoryScannerPlugin@129c322f]'.

        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerI
mpl.java:85)
        at com.buschmais.jqassistant.scm.cli.task.ScanTask.scan(ScanTask.java:12
6)
        at com.buschmais.jqassistant.scm.cli.task.ScanTask.executeTask(ScanTask.
java:73)
        at com.buschmais.jqassistant.scm.cli.task.AbstractTask.run(AbstractTask.
java:61)
        at com.buschmais.jqassistant.scm.cli.Main.executeTask(Main.java:235)
        at com.buschmais.jqassistant.scm.cli.Main.interpretCommandLine(Main.java
:187)
        at com.buschmais.jqassistant.scm.cli.Main.run(Main.java:73)
        at com.buschmais.jqassistant.scm.cli.Main.main(Main.java:44)
Caused by: java.lang.IllegalStateException: Unexpected problem while scanning: i
tem='com.buschmais.jqassistant.plugin.common.impl.scanner.BufferedFileResource@3
62c48c', path='/FastInfoset-1.2.12.jar', scope='NONE', pipeline='[com.buschmais.
jqassistant.plugin.common.impl.scanner.FileResourceScannerPlugin@29b4444a, com.b
uschmais.jqassistant.plugin.java.impl.scanner.JarScannerPlugin@2d34866a]'.
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerI
mpl.java:85)
        at com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContainer
ScannerPlugin.scan(AbstractContainerScannerPlugin.java:56)
        at com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContainer
ScannerPlugin.scan(AbstractContainerScannerPlugin.java:31)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerI
mpl.java:77)
        ... 7 more
Caused by: java.lang.IllegalStateException: Unexpected problem while scanning: i
tem='java.util.zip.ZipFile@574327ed', path='/FastInfoset-1.2.12.jar', scope='CLA
SSPATH', pipeline='[com.buschmais.jqassistant.plugin.common.impl.scanner.ZipFile
ScannerPlugin@1b5cf611]'.
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerI
mpl.java:85)
        at com.buschmais.jqassistant.plugin.common.api.scanner.AbstractArchiveSc
annerPlugin.scan(AbstractArchiveScannerPlugin.java:50)
        at com.buschmais.jqassistant.plugin.common.api.scanner.AbstractArchiveSc
annerPlugin.scan(AbstractArchiveScannerPlugin.java:21)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerI
mpl.java:77)
        ... 10 more
Caused by: java.lang.IllegalStateException: Unexpected problem while scanning: i
tem='com.buschmais.jqassistant.plugin.common.impl.scanner.ZipFileScannerPlugin$3
@7a51dc38', path='/META-INF/maven/com.sun.xml.fastinfoset/FastInfoset/pom.xml',
scope='CLASSPATH', pipeline='[com.buschmais.jqassistant.plugin.common.impl.scann
er.FileResourceScannerPlugin@29b4444a, com.buschmais.jqassistant.plugin.maven3.i
mpl.scanner.MavenPomXmlFileScannerPlugin@1382a7d8, com.buschmais.jqassistant.plu
gin.xml.impl.scanner.XmlFileScannerPlugin@402feb85]'.
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerI
mpl.java:85)
        at com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContainer
ScannerPlugin.scan(AbstractContainerScannerPlugin.java:56)
        at com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContainer
ScannerPlugin.scan(AbstractContainerScannerPlugin.java:31)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerI
mpl.java:77)
        ... 13 more
Caused by: java.lang.IllegalStateException: Unexpected problem while scanning: i
tem='com.sun.xml.fastinfoset:FastInfoset:jar:1.2.12', path='/META-INF/maven/com.
sun.xml.fastinfoset/FastInfoset/pom.xml', scope='CLASSPATH', pipeline='[com.busc
hmais.jqassistant.plugin.maven3.impl.scanner.MavenModelScannerPlugin@22b3b5d0]'.

        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerI
mpl.java:85)
        at com.buschmais.jqassistant.plugin.maven3.impl.scanner.AbstractMavenPom
ScannerPlugin.scan(AbstractMavenPomScannerPlugin.java:61)
        at com.buschmais.jqassistant.plugin.maven3.impl.scanner.AbstractMavenPom
ScannerPlugin.scan(AbstractMavenPomScannerPlugin.java:25)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerI
mpl.java:77)
        ... 16 more
Caused by: java.lang.NullPointerException
        at com.buschmais.jqassistant.plugin.maven3.impl.scanner.MavenModelScanne
rPlugin.createMavenPomXmlDescriptor(MavenModelScannerPlugin.java:91)
        at com.buschmais.jqassistant.plugin.maven3.impl.scanner.MavenModelScanne
rPlugin.scan(MavenModelScannerPlugin.java:57)
        at com.buschmais.jqassistant.plugin.maven3.impl.scanner.MavenModelScanne
rPlugin.scan(MavenModelScannerPlugin.java:32)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerI
mpl.java:77)
        ... 19 more

**Comment by obfischer** [comment]
Can you please add the output of `mvn --version` to this issue?

**Comment by gavin834** [comment]
mvn --version
Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 16:22:2
2+0100)
Maven home: C:\maven\apache-maven-3.1.1\bin\..
Java version: 1.8.0, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0\jre
Default locale: en_GB, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"

**Comment by DirkMahler** [comment]
This issue has already been reported and has been fixed, see #272.-You're using the CLI, could I ask you to try the latest snapshot from https://oss.sonatype.org/content/repositories/snapshots/com/buschmais/jqassistant/distribution/jqassistant.distribution/1.1.0-RC2-SNAPSHOT/ ?

**Comment by gavin834** [comment]
Thanks Dirk, I can confirm the example works with the latest snapshot. Sorry about the duplicate error report.
