### ISSUE TITLE
Exception while scanning glassfish-embedded-all-3.1.2.2.jar

### ISSUE THREAD

**Issue by DirkMahler** [buschmais/jqassistant#291]
```
Caused by: java.lang.IllegalArgumentException: Other node is null.
        at org.neo4j.kernel.impl.core.NodeProxy.createRelationshipTo(NodeProxy.java:467)
        at com.buschmais.xo.neo4j.impl.datastore.Neo4jRelationManager.createRelation(Neo4jRelationManager.java:47)
        at com.buschmais.xo.neo4j.impl.datastore.Neo4jRelationManager.createRelation(Neo4jRelationManager.java:20)
        at com.buschmais.xo.impl.EntityPropertyManager.createReference(EntityPropertyManager.java:181)
        at com.buschmais.xo.impl.EntityPropertyManager.createRelation(EntityPropertyManager.java:161)
        at com.buschmais.xo.impl.EntityPropertyManager.createEntityReference(EntityPropertyManager.java:40)
        at com.buschmais.xo.impl.proxy.collection.EntityCollectionProxy.add(EntityCollectionProxy.java:40)
        at com.buschmais.xo.impl.proxy.collection.ListProxy.add(ListProxy.java:78)
        at com.buschmais.jqassistant.plugin.common.api.scanner.ContainerFileResolverStrategy.createHierarchy(ContainerFileResolverStrategy.java:69)
        at com.buschmais.jqassistant.plugin.common.api.scanner.ContainerFileResolverStrategy.flush(ContainerFileResolverStrategy.java:51)
        at com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContainerScannerPlugin.scan(AbstractContainerScannerPlugin.java:58)
        at com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContainerScannerPlugin.scan(AbstractContainerScannerPlugin.java:29)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:69)
        ... 13 more
```

**Comment by DirkMahler** [comment]
The JAR file contains the same class twice but in different locations which leads to wrong resolving of nodes:
```
/com/sun/xml/xsom/XSModelGroupDecl.class
/1.0/com/sun/xml/xsom/XSModelGroupDecl.class
```
