### ISSUE TITLE
Failure during scan of a larger project

### ISSUE THREAD

**Issue by khmarbaise** [buschmais/jqassistant#292]
[ERROR] Failed to execute goal com.buschmais.jqassistant.scm:jqassistant-maven-plugin:1.1.0-RC2:scan (default) on project base-util: Execution default of goal com.buschmais.jqassistant.scm:jqassistant-maven-plugin:1.1.0-RC2:scan failed: Unexpected problem while scanning: item='MavenProject: xyz:util:1.0.0-SNAPSHOT @ c:\project\pom.xml', path='c:\project\pom.xml', scope='PROJECT', pipeline='[com.buschmais.jqassistant.plugin.maven3.impl.scanner.MavenProjectScannerPlugin@3c84310f]'. Other node is null. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.buschmais.jqassistant.scm:jqassistant-maven-plugin:1.1.0-RC2:scan (default) on project base-util: Execution default of goal com.buschmais.jqassistant.scm:jqassistant-maven-plugin:1.1.0-RC2:scan failed: Unexpected problem while scanning: item='MavenProject: xyz:util:1.0.0-SNAPSHOT @ c:\project\pom.xml', path='c:\project\pom.xml', scope='PROJECT', pipeline='[com.buschmais.jqassistant.plugin.maven3.impl.scanner.MavenProjectScannerPlugin@3c84310f]'.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.buschmais.jqassistant.scm:jqassistant-maven-plugin:1.1.0-RC2:scan failed: Unexpected problem while scanning: item='MavenProject: xyz:util:1.0.0-SNAPSHOT @ c:\project\pom.xml', path='c:\project\pom.xml', scope='PROJECT', pipeline='[com.buschmais.jqassistant.plugin.maven3.impl.scanner.MavenProjectScannerPlugin@3c84310f]'.
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    ... 19 more
Caused by: java.lang.IllegalStateException: Unexpected problem while scanning: item='MavenProject: xyz:util:1.0.0-SNAPSHOT @ c:\project\pom.xml', path='c:\project\pom.xml', scope='PROJECT', pipeline='[com.buschmais.jqassistant.plugin.maven3.impl.scanner.MavenProjectScannerPlugin@3c84310f]'.
    at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:73)
    at com.buschmais.jqassistant.scm.maven.ScanMojo.execute(ScanMojo.java:78)
    at com.buschmais.jqassistant.scm.maven.AbstractModuleMojo$1.run(AbstractModuleMojo.java:19)
    at com.buschmais.jqassistant.scm.maven.AbstractMojo.execute(AbstractMojo.java:287)
    at com.buschmais.jqassistant.scm.maven.AbstractMojo.execute(AbstractMojo.java:262)
    at com.buschmais.jqassistant.scm.maven.AbstractModuleMojo.doExecute(AbstractModuleMojo.java:16)
    at com.buschmais.jqassistant.scm.maven.AbstractMojo.execute(AbstractMojo.java:143)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
    ... 20 more
Caused by: java.lang.IllegalArgumentException: Other node is null.
    at org.neo4j.kernel.impl.core.NodeProxy.createRelationshipTo(NodeProxy.java:467)
    at com.buschmais.xo.neo4j.impl.datastore.Neo4jRelationManager.createRelation(Neo4jRelationManager.java:47)
    at com.buschmais.xo.neo4j.impl.datastore.Neo4jRelationManager.createRelation(Neo4jRelationManager.java:20)
    at com.buschmais.xo.impl.EntityPropertyManager.createReference(EntityPropertyManager.java:181)
    at com.buschmais.xo.impl.EntityPropertyManager.createRelation(EntityPropertyManager.java:161)
    at com.buschmais.xo.impl.EntityPropertyManager.createRelationReference(EntityPropertyManager.java:49)
    at com.buschmais.xo.impl.XOManagerImpl.createByExample(XOManagerImpl.java:266)
    at com.buschmais.xo.impl.XOManagerImpl.create(XOManagerImpl.java:252)
    at com.buschmais.jqassistant.core.store.impl.AbstractGraphStore.create(AbstractGraphStore.java:64)
    at com.buschmais.jqassistant.plugin.maven3.impl.scanner.MavenProjectScannerPlugin.addDependencies(MavenProjectScannerPlugin.java:218)
    at com.buschmais.jqassistant.plugin.maven3.impl.scanner.MavenProjectScannerPlugin.scan(MavenProjectScannerPlugin.java:78)
    at com.buschmais.jqassistant.plugin.maven3.impl.scanner.MavenProjectScannerPlugin.scan(MavenProjectScannerPlugin.java:39)
    at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:69)
    ... 27 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :base-util
[INFO] Closing store in directory 'C:\project\target\jqassistant\store'.

**Comment by DirkMahler** [comment]
The error indicates a problem with the maven module itself. Can you reproduce it if you run mvn jqassistant:scan only from this module?

BTW: sorry for the inconvenience but we changed exception handling to be more "nervous" in 1.1.0 to better identify implementation errors in the plugins.

**Comment by khmarbaise** [comment]
Hi Dirk, can you be a little bit more accurate what you mean by `problem with maven module itself` ?

**Comment by DirkMahler** [comment]
Maybe a wrong assumption on my side: I assume that by "larger project" you mean a multi-module Maven project? If this is correct I need to know if the error also occurs if you run the scan only in the module where the build fails.

**Comment by khmarbaise** [comment]
Can check this on thursday...

**Comment by DirkMahler** [comment]
Do have an update on this issue?

**Comment by DirkMahler** [comment]
Is the problem still existing?

**Comment by khmarbaise** [comment]
Outch sorry...just forgot about that

**Comment by DirkMahler** [comment]
No problem, just performing some "garbage collection".
