### ISSUE TITLE
Labeled List in Asciidoc document breaks analyse

### ISSUE THREAD

**Issue by grossh** [buschmais/jqassistant#395]
A simple labeled list, as defined in https://asciidoctor.org/docs/user-manual/#labeled-list
will break the analysis.
The error can be reproduced by simply adding these lines to one of the asciidoc files in the petclinic demo project:
```asciidoc
Operating System::
 Linux
Database:: 
 Oracle
```
It will create the following exception and the build breaks:
```
Exception in thread "main" java.lang.ClassCastException: org.jruby.specialized.RubyArrayTwoObject cannot be cast to org.asciidoctor.ast.AbstractBlock
	at org.asciidoctor.internal.JRubyAsciidoctor.getContents(JRubyAsciidoctor.java:202)
	at org.asciidoctor.internal.JRubyAsciidoctor.getContentPartFromBlock(JRubyAsciidoctor.java:218)
	at org.asciidoctor.internal.JRubyAsciidoctor.getContents(JRubyAsciidoctor.java:203)
	at org.asciidoctor.internal.JRubyAsciidoctor.getContentPartFromBlock(JRubyAsciidoctor.java:218)
	at org.asciidoctor.internal.JRubyAsciidoctor.getContents(JRubyAsciidoctor.java:203)
	at org.asciidoctor.internal.JRubyAsciidoctor.getContentPartFromBlock(JRubyAsciidoctor.java:218)
	at org.asciidoctor.internal.JRubyAsciidoctor.getContents(JRubyAsciidoctor.java:203)
	at org.asciidoctor.internal.JRubyAsciidoctor.toDocument(JRubyAsciidoctor.java:184)
	at org.asciidoctor.internal.JRubyAsciidoctor.readDocumentStructure(JRubyAsciidoctor.java:246)
	at org.asciidoctor.internal.JRubyAsciidoctor.readDocumentStructure(JRubyAsciidoctor.java:252)
	at com.buschmais.jqassistant.core.rule.impl.reader.AsciiDocRuleSetReader.readDocument(AsciiDocRuleSetReader.java:105)
	at com.buschmais.jqassistant.core.rule.impl.reader.AsciiDocRuleSetReader.read(AsciiDocRuleSetReader.java:81)
	at com.buschmais.jqassistant.core.rule.impl.reader.CompoundRuleSetReader.read(CompoundRuleSetReader.java:27)
	at com.buschmais.jqassistant.commandline.task.AbstractAnalyzeTask.getAvailableRules(AbstractAnalyzeTask.java:72)
	at com.buschmais.jqassistant.commandline.task.AnalyzeTask.executeTask(AnalyzeTask.java:78)
	at com.buschmais.jqassistant.commandline.task.AbstractTask.run(AbstractTask.java:68)
	at com.buschmais.jqassistant.commandline.Main.executeTask(Main.java:253)
	at com.buschmais.jqassistant.commandline.Main.interpretCommandLine(Main.java:205)
	at com.buschmais.jqassistant.commandline.Main.run(Main.java:91)
	at com.buschmais.jqassistant.commandline.Main.main(Main.java:62)
```

**Comment by DirkMahler** [comment]
This is known issue and has already been fixed. Will be available in a couple of days within the 1.4 release.
